const GOAL_CATEGORIES = {
  'weight-loss': { id: 'weight-loss', label: 'Weight Loss', subtitle: 'Metabolic & GLP-1 research', products: ['semaglutide'] },
  'tissue-repair': { id: 'tissue-repair', label: 'Tissue Repair', subtitle: 'Recovery & structural research', products: ['bpc-157', 'tb-500', 'recovery-stack'] },
  'growth-hormone': { id: 'growth-hormone', label: 'Growth Hormone', subtitle: 'GH axis & secretagogue research', products: ['ipamorelin', 'cjc-1295', 'gh-stack'] },
  'anti-aging': { id: 'anti-aging', label: 'Anti-Aging', subtitle: 'Longevity & cellular research', products: ['ghk-cu', 'ipamorelin', 'cjc-1295'] },
  'skin-research': { id: 'skin-research', label: 'Skin & Beauty', subtitle: 'Cosmetic & matrix research', products: ['ghk-cu', 'bpc-157'] },
  'metabolic': { id: 'metabolic', label: 'Metabolic Health', subtitle: 'Glucose & endocrine pathways', products: ['semaglutide', 'ipamorelin'] },
};

const PRODUCTS = {
  'bpc-157': {
    id: 'bpc-157', name: 'BPC-157', tagline: 'Body Protection Compound-157',
    description: 'A synthetic pentadecapeptide derived from human gastric juice. Widely studied in tissue repair and angiogenesis research models.',
    longDescription: 'BPC-157 is a 15-amino acid synthetic peptide originally isolated from gastric juice. In preclinical models it has been studied for effects on tendon and ligament healing, angiogenesis via VEGFR2 signaling, and gastrointestinal cytoprotection.',
    price: 49, defaultVariant: '5mg',
    variants: { '5mg': { label: '5mg', price: 49 }, '10mg': { label: '10mg', price: 85 } },
    sizes: ['5mg', '10mg'], purity: '≥99%', form: 'Lyophilized powder',
    storage: '−20°C long-term; 2–8°C reconstituted', cas: '137525-51-0',
    sequence: 'GEPPPGKPADDAGLV', molecularWeight: '1,419.6 g/mol', color: '#3b82f6',
    categories: ['tissue-repair', 'skin-research'],
    currentLot: 'RC-BPC26-0412', lotPurity: '99.7%',
    researchAreas: ['Tendon & ligament repair', 'Angiogenesis', 'GI cytoprotection', 'Fibroblast migration', 'Wound healing models'],
    mechanism: 'Modulates VEGFR2 and nitric oxide pathways, promotes fibroblast recruitment and extracellular matrix remodeling in preclinical tissue injury models.',
    researchHighlights: ['Studied for accelerated tendon outgrowth and collagen fiber organization in rodent models', 'Associated with VEGF upregulation and endothelial cell proliferation in wound healing assays', 'Investigated for protective effects on gastric mucosa and GI tract integrity', 'Commonly paired with TB-500 in recovery-focused research protocols'],
    reconstitution: 'Reconstitute with bacteriostatic water (BAC). Typical protocol: add 1–2 mL BAC per 5mg vial.',
    handling: 'Handle under aseptic conditions. Avoid repeated freeze-thaw cycles.',
  },
  'tb-500': {
    id: 'tb-500', name: 'TB-500', tagline: 'Thymosin Beta-4 Fragment',
    description: 'A synthetic version of the active region of thymosin beta-4. Commonly used in cell migration and wound healing research.',
    longDescription: 'TB-500 is a synthetic peptide fragment corresponding to the actin-binding domain of thymosin beta-4.',
    price: 65, defaultVariant: '5mg', variants: { '5mg': { label: '5mg', price: 65 } },
    sizes: ['5mg'], purity: '≥99%', form: 'Lyophilized powder',
    storage: '−20°C long-term; 2–8°C reconstituted', cas: '77591-33-4',
    sequence: 'LKKTETQ', molecularWeight: '4,963.5 g/mol', color: '#8b5cf6',
    categories: ['tissue-repair'], currentLot: 'RC-TB26-0388', lotPurity: '99.5%',
    researchAreas: ['Cell migration', 'Angiogenesis', 'Actin regulation', 'Musculoskeletal repair', 'Inflammation models'],
    mechanism: 'Promotes actin polymerization and cell motility, facilitating migration of repair cells to injury sites.',
    researchHighlights: ['Derived from thymosin beta-4, first characterized in the 1960s', 'Studied for enhanced wound closure and granulation tissue formation', 'Investigated in musculoskeletal and soft tissue injury research models', 'Often researched alongside BPC-157'],
    reconstitution: 'Add 1–2 mL bacteriostatic water per 5mg vial.',
    handling: 'Lyophilized form stable at −20°C. Reconstituted: 2–8°C, use within 14–30 days.',
  },
  'semaglutide': {
    id: 'semaglutide', name: 'Semaglutide', tagline: 'GLP-1 Receptor Agonist',
    description: 'A glucagon-like peptide-1 analog modified with a fatty acid side chain. Studied extensively in metabolic and glucose regulation research.',
    longDescription: 'Semaglutide is a long-acting GLP-1 receptor agonist with structural modifications for extended half-life.',
    price: 89, defaultVariant: '2mg', variants: { '2mg': { label: '2mg', price: 89 } },
    sizes: ['2mg'], purity: '≥98%', form: 'Lyophilized powder',
    storage: '−20°C long-term; 2–8°C reconstituted', cas: '910463-68-2',
    sequence: 'Modified GLP-1 analog', molecularWeight: '4,113.6 g/mol', color: '#10b981',
    categories: ['weight-loss', 'metabolic'], currentLot: 'RC-SEM26-0401', lotPurity: '98.4%',
    researchAreas: ['GLP-1 receptor signaling', 'Glucose homeostasis', 'Appetite regulation', 'Insulin secretion', 'Metabolic pathways'],
    mechanism: 'Binds and activates GLP-1 receptors, enhancing glucose-dependent insulin secretion in preclinical endocrine models.',
    researchHighlights: ['Developed with albumin-binding modifications for extended receptor engagement', 'Extensively characterized in peer-reviewed metabolic literature', 'Key reference compound for GLP-1 pathway research laboratories'],
    reconstitution: 'Add 1 mL BAC per 2mg vial for 2mg/mL concentration.',
    handling: 'Light-sensitive when reconstituted. Store at 2–8°C.',
  },
  'ipamorelin': {
    id: 'ipamorelin', name: 'Ipamorelin', tagline: 'Growth Hormone Secretagogue',
    description: 'A selective ghrelin receptor agonist and growth hormone secretagogue.',
    longDescription: 'Ipamorelin is a selective growth hormone secretagogue developed in the 1990s with minimal off-target hormonal effects.',
    price: 39, defaultVariant: '2mg',
    variants: { '2mg': { label: '2mg', price: 39 }, '5mg': { label: '5mg', price: 69 } },
    sizes: ['2mg', '5mg'], purity: '≥99%', form: 'Lyophilized powder',
    storage: '−20°C long-term; 2–8°C reconstituted', cas: '170851-70-4',
    sequence: 'Aib-His-D-2-Nal-D-Phe-Lys', molecularWeight: '711.9 g/mol', color: '#f59e0b',
    categories: ['growth-hormone', 'anti-aging', 'metabolic'], currentLot: 'RC-IPA26-0375', lotPurity: '99.6%',
    researchAreas: ['GH secretion', 'Pituitary signaling', 'Somatotroph axis', 'Body composition models', 'Bone density research'],
    mechanism: 'Selectively stimulates GH release via ghrelin receptor activation with minimal cortisol/prolactin elevation.',
    researchHighlights: ['Developed as selective alternative to GHRP-6 and GHRP-2', 'Commonly combined with CJC-1295 in GH axis research', 'Used in lean mass and bone metabolism models'],
    reconstitution: 'Add 1–2 mL bacteriostatic water per vial.',
    handling: 'Store lyophilized at −20°C. Reconstituted: 2–8°C, 30 days.',
  },
  'cjc-1295': {
    id: 'cjc-1295', name: 'CJC-1295', tagline: 'GHRH Analog (no DAC)',
    description: 'A tetrasubstituted GHRH analog without DAC. Studied in GHRH receptor binding research.',
    longDescription: 'CJC-1295 (no DAC) enables pulsatile growth hormone release studies.',
    price: 45, defaultVariant: '2mg', variants: { '2mg': { label: '2mg', price: 45 } },
    sizes: ['2mg'], purity: '≥99%', form: 'Lyophilized powder',
    storage: '−20°C long-term; 2–8°C reconstituted', cas: '863288-34-0',
    sequence: 'Modified GHRH(1-29)', molecularWeight: '3,647.1 g/mol', color: '#ec4899',
    categories: ['growth-hormone', 'anti-aging'], currentLot: 'RC-CJC26-0362', lotPurity: '99.4%',
    researchAreas: ['GHRH receptor binding', 'GH pulse dynamics', 'Somatotroph research', 'Endocrine signaling', 'IGF-1 pathway studies'],
    mechanism: 'Binds GHRH receptors on pituitary somatotrophs, stimulating growth hormone release.',
    researchHighlights: ['No-DAC variant preferred for pulsatility research', 'Frequently combined with Ipamorelin', 'Used to investigate IGF-1 signaling cascades'],
    reconstitution: 'Reconstitute with 1–2 mL bacteriostatic water per 2mg vial.',
    handling: 'Protect from light and moisture.',
  },
  'ghk-cu': {
    id: 'ghk-cu', name: 'GHK-Cu', tagline: 'Copper Peptide Complex',
    description: 'A naturally occurring copper complex researched in extracellular matrix and collagen studies.',
    longDescription: 'GHK-Cu is extensively studied in cosmetic and dermatological research for collagen synthesis and matrix remodeling.',
    price: 35, defaultVariant: '50mg',
    variants: { '50mg': { label: '50mg', price: 35 }, '100mg': { label: '100mg', price: 58 } },
    sizes: ['50mg', '100mg'], purity: '≥99%', form: 'Lyophilized powder',
    storage: '−20°C long-term; 2–8°C reconstituted', cas: '49557-75-7',
    sequence: 'GHK-Cu²⁺', molecularWeight: '340.9 g/mol', color: '#06b6d4',
    categories: ['anti-aging', 'skin-research'], currentLot: 'RC-GHK26-0395', lotPurity: '99.8%',
    researchAreas: ['Collagen synthesis', 'Skin remodeling', 'Hair follicle research', 'Antioxidant activity', 'Gene expression modulation'],
    mechanism: 'Copper-dependent peptide modulating extracellular matrix formation and collagen production.',
    researchHighlights: ['Identified by Pickart in the 1970s', 'Studied for collagen and GAG synthesis upregulation', 'Higher-dose vials for topical and in-vitro protocols'],
    reconstitution: 'Use 2–3 mL BAC for 50mg; 3–5 mL for 100mg.',
    handling: 'Avoid reducing agents. Store reconstituted at 2–8°C, 21 days.',
  },
  'recovery-stack': {
    id: 'recovery-stack', name: 'Recovery Stack', tagline: 'BPC-157 + TB-500 Bundle',
    description: 'Combined BPC-157 (5mg) and TB-500 (5mg) for complementary tissue repair pathway research.',
    longDescription: 'Our Recovery Stack pairs BPC-157 and TB-500 — the two most complementary peptides in structural and angiogenic research.',
    price: 99, defaultVariant: 'bundle', isBundle: true,
    variants: { bundle: { label: 'BPC-157 5mg + TB-500 5mg', price: 99 } },
    sizes: ['Bundle'], purity: '≥99%', form: 'Lyophilized powder',
    storage: '−20°C long-term', cas: 'Bundle', sequence: '—', molecularWeight: '—',
    color: '#6366f1', categories: ['tissue-repair'],
    currentLot: 'RC-RS26-0408', lotPurity: '99.6%',
    researchAreas: ['Tissue repair', 'Angiogenesis', 'Cell migration', 'Recovery models'],
    mechanism: 'Dual-pathway approach: BPC-157 (VEGFR2/NO signaling) + TB-500 (actin migration).',
    researchHighlights: ['Bundle pricing — confirmed at checkout', 'Same-batch COAs included for both compounds', 'Most popular pairing in recovery research'],
    reconstitution: 'Reconstitute each vial separately per individual compound protocols.',
    handling: 'Store all vials at −20°C until use.',
  },
  'gh-stack': {
    id: 'gh-stack', name: 'GH Research Stack', tagline: 'Ipamorelin + CJC-1295 Bundle',
    description: 'Ipamorelin (2mg) + CJC-1295 no DAC (2mg) for GH axis research protocols.',
    longDescription: 'The standard dual-pathway GH research combination: GHRH receptor activation plus ghrelin receptor stimulation.',
    price: 72, defaultVariant: 'bundle', isBundle: true,
    variants: { bundle: { label: 'Ipamorelin 2mg + CJC-1295 2mg', price: 72 } },
    sizes: ['Bundle'], purity: '≥99%', form: 'Lyophilized powder',
    storage: '−20°C long-term', cas: 'Bundle', sequence: '—', molecularWeight: '—',
    color: '#a855f7', categories: ['growth-hormone', 'anti-aging'],
    currentLot: 'RC-GH26-0390', lotPurity: '99.5%',
    researchAreas: ['GH axis', 'Pituitary signaling', 'IGF-1 pathways'],
    mechanism: 'CJC-1295 activates GHRH receptors; Ipamorelin activates ghrelin receptors — modeling dual-input GH regulation.',
    researchHighlights: ['Bundle pricing — confirmed at checkout', 'Standard pairing in endocrine research literature'],
    reconstitution: 'Reconstitute each vial separately.',
    handling: 'Store at −20°C. Reconstituted: 2–8°C.',
  },
  'bac-water': {
    id: 'bac-water', name: 'Bacteriostatic Water', tagline: '30mL Reconstitution Solution',
    description: 'Sterile bacteriostatic water for peptide reconstitution. 0.9% benzyl alcohol preservative.',
    longDescription: 'USP-grade bacteriostatic water for laboratory reconstitution of lyophilized peptides.',
    price: 12, defaultVariant: '30ml', isAddon: true,
    variants: { '30ml': { label: '30mL', price: 12 } },
    sizes: ['30mL'], purity: 'USP Grade', form: 'Liquid solution',
    storage: '15–25°C; refrigerate after opening', cas: 'N/A', sequence: '—',
    molecularWeight: '—', color: '#94a3b8', categories: [],
    researchAreas: ['Reconstitution'], mechanism: 'Sterile aqueous diluent with bacteriostatic preservative.',
    researchHighlights: ['Recommended for all lyophilized peptide reconstitution', 'Add at checkout for convenience'],
    reconstitution: 'Ready to use. Draw required volume with sterile syringe.',
    handling: 'Single-user vial. Discard 28 days after first puncture.',
  },
};

window.PRODUCTS = PRODUCTS;
window.GOAL_CATEGORIES = GOAL_CATEGORIES;