const GOAL_CATEGORIES = {
  'metabolic-research': {
    id: 'metabolic-research',
    label: 'Metabolic Research Compounds',
    subtitle: 'GLP-1 pathway & endocrine signaling',
    products: ['semaglutide', 'ipamorelin'],
  },
  'tissue-research': {
    id: 'tissue-research',
    label: 'Tissue Research Compounds',
    subtitle: 'Structural peptide & migration models',
    products: ['bpc-157', 'tb-500', 'recovery-stack'],
  },
  'endocrine-research': {
    id: 'endocrine-research',
    label: 'Endocrine Research Compounds',
    subtitle: 'Peptide receptor signaling models',
    products: ['ipamorelin', 'cjc-1295', 'gh-stack'],
  },
  'matrix-research': {
    id: 'matrix-research',
    label: 'Matrix Research Compounds',
    subtitle: 'Extracellular matrix & collagen assays',
    products: ['ghk-cu', 'bpc-157'],
  },
};

/** Legacy goal URL aliases → current category ids */
const GOAL_ALIASES = {
  'weight-loss': 'metabolic-research',
  'tissue-repair': 'tissue-research',
  'growth-hormone': 'endocrine-research',
  'anti-aging': 'matrix-research',
  'skin-research': 'matrix-research',
  metabolic: 'metabolic-research',
};

const PRODUCTS = {
  'bpc-157': {
    id: 'bpc-157',
    name: 'BPC-157',
    tagline: 'Pentadecapeptide — lyophilized research material',
    description: 'BPC-157 (Pentadecapeptide) — 5mg / 10mg lyophilized vial for in-vitro research.',
    longDescription: 'Synthetic 15-amino acid pentadecapeptide (GEPPPGKPADDAGLV) supplied as a lyophilized powder for qualified laboratory research. HPLC-verified identity and purity documented on batch-specific COA.',
    price: 49,
    defaultVariant: '5mg',
    variants: { '5mg': { label: '5mg', price: 49 }, '10mg': { label: '10mg', price: 85 } },
    sizes: ['5mg', '10mg'],
    purity: '≥99%',
    form: 'Lyophilized powder',
    storage: 'Store sealed lyophilized material per your institution\'s cold-storage protocols for peptide reagents.',
    cas: '137525-51-0',
    sequence: 'GEPPPGKPADDAGLV',
    molecularWeight: '1,419.6 g/mol',
    color: '#3b82f6',
    categories: ['tissue-research', 'matrix-research'],
    currentLot: 'RC-BPC26-0412',
    lotPurity: '99.7%',
    researchAreas: ['Peptide identity assays', 'Cell culture models', 'Binding studies', 'Analytical reference standard'],
    mechanism: 'Synthetic pentadecapeptide supplied for analytical and in-vitro laboratory characterization.',
    researchHighlights: [
      'HPLC purity ≥99% with mass spectrometry identity confirmation',
      'Lyophilized format for laboratory stability studies',
      'Batch-specific COA included with every order',
      'For in-vitro research use only — not for human or animal consumption',
    ],
    reconstitution: 'Prepare per your laboratory standard operating procedures for lyophilized peptide reagents.',
    handling: 'Handle under qualified laboratory conditions. Follow institutional protocols for peptide reagent storage and documentation.',
  },
  'tb-500': {
    id: 'tb-500',
    name: 'TB-500',
    tagline: 'Synthetic heptapeptide (LKKTETQ) — 5mg lyophilized vial',
    description: 'TB-500 — synthetic heptapeptide supplied as a 5mg lyophilized vial for in-vitro research.',
    longDescription: 'Synthetic heptapeptide (sequence LKKTETQ) supplied as a lyophilized powder for qualified laboratory research. Identity and purity verified by HPLC and mass spectrometry.',
    price: 65,
    defaultVariant: '5mg',
    variants: { '5mg': { label: '5mg', price: 65 } },
    sizes: ['5mg'],
    purity: '≥99%',
    form: 'Lyophilized powder',
    storage: 'Store sealed lyophilized material per standard cold-storage protocols for peptide reagents.',
    cas: '77591-33-4',
    sequence: 'LKKTETQ',
    molecularWeight: '886.0 g/mol',
    color: '#8b5cf6',
    categories: ['tissue-research'],
    currentLot: 'RC-TB26-0388',
    lotPurity: '99.5%',
    researchAreas: ['Cell migration assays', 'Actin-binding studies', 'Analytical characterization', 'In-vitro signaling models'],
    mechanism: 'Synthetic heptapeptide reagent for laboratory assay development and in-vitro studies.',
    researchHighlights: [
      'Defined sequence LKKTETQ for reproducible laboratory protocols',
      'HPLC-verified purity with MS identity confirmation',
      'Lyophilized presentation for research stability',
      'Research use only — not for human or animal consumption',
    ],
    reconstitution: 'Prepare per your laboratory standard operating procedures for lyophilized peptide reagents.',
    handling: 'Store lyophilized material per institutional cold-storage requirements.',
  },
  'semaglutide': {
    id: 'semaglutide',
    name: 'Semaglutide',
    tagline: 'GLP-1 analog — research-grade 2mg',
    description: 'Semaglutide (GLP-1 analog) — research-grade 2mg lyophilized vial for in-vitro research.',
    longDescription: 'Modified GLP-1 analog supplied as a lyophilized powder for qualified endocrine and metabolic pathway research in laboratory settings.',
    price: 89,
    defaultVariant: '2mg',
    variants: { '2mg': { label: '2mg', price: 89 } },
    sizes: ['2mg'],
    purity: '≥98%',
    form: 'Lyophilized powder',
    storage: 'Store sealed lyophilized material per standard cold-storage protocols for peptide reagents.',
    cas: '910463-68-2',
    sequence: 'Modified GLP-1 analog',
    molecularWeight: '4,113.6 g/mol',
    color: '#10b981',
    categories: ['metabolic-research'],
    currentLot: 'RC-SEM26-0401',
    lotPurity: '98.4%',
    researchAreas: ['GLP-1 receptor assays', 'Metabolic pathway models', 'Receptor binding studies', 'Analytical reference standard'],
    mechanism: 'GLP-1 analog peptide reagent for in-vitro receptor and signaling research.',
    researchHighlights: [
      'Research-grade 2mg lyophilized format for assay preparation',
      'HPLC purity ≥98% with MS identity confirmation',
      'Widely referenced in published GLP-1 pathway literature',
      'For laboratory research only — not for human or animal consumption',
    ],
    reconstitution: 'Prepare per your laboratory standard operating procedures for lyophilized peptide reagents.',
    handling: 'Protect prepared solutions from light per institutional protocol.',
  },
  'ipamorelin': {
    id: 'ipamorelin',
    name: 'Ipamorelin',
    tagline: 'Synthetic pentapeptide — 2mg lyophilized vial',
    description: 'Ipamorelin — synthetic pentapeptide supplied in 2mg and 5mg lyophilized vials for in-vitro research.',
    longDescription: 'Synthetic pentapeptide (Aib-His-D-2-Nal-D-Phe-Lys) supplied as a lyophilized powder for qualified endocrine signaling research in laboratory settings.',
    price: 39,
    defaultVariant: '2mg',
    variants: { '2mg': { label: '2mg', price: 39 }, '5mg': { label: '5mg', price: 69 } },
    sizes: ['2mg', '5mg'],
    purity: '≥99%',
    form: 'Lyophilized powder',
    storage: 'Store sealed lyophilized material per standard cold-storage protocols for peptide reagents.',
    cas: '170851-70-4',
    sequence: 'Aib-His-D-2-Nal-D-Phe-Lys',
    molecularWeight: '711.9 g/mol',
    color: '#f59e0b',
    categories: ['endocrine-research', 'metabolic-research'],
    currentLot: 'RC-IPA26-0375',
    lotPurity: '99.6%',
    researchAreas: ['GHS-R receptor assays', 'Pituitary cell models', 'Peptide binding studies', 'Analytical characterization'],
    mechanism: 'Synthetic pentapeptide reagent for in-vitro endocrine signaling research.',
    researchHighlights: [
      'Selective laboratory reference compound for GHS-R studies',
      'Available in 2mg and 5mg lyophilized vials',
      'HPLC-verified with batch-specific COA',
      'Research use only — not for human or animal consumption',
    ],
    reconstitution: 'Prepare per your laboratory standard operating procedures for lyophilized peptide reagents.',
    handling: 'Document batch and preparation date per institutional protocol.',
  },
  'cjc-1295': {
    id: 'cjc-1295',
    name: 'CJC-1295',
    tagline: 'Modified GHRH(1-29) peptide — 2mg lyophilized vial',
    description: 'CJC-1295 (no DAC) — modified GHRH(1-29) peptide, 2mg lyophilized vial for in-vitro research.',
    longDescription: 'Tetrasubstituted GHRH(1-29) peptide supplied without DAC modification as a lyophilized powder for qualified endocrine receptor research.',
    price: 45,
    defaultVariant: '2mg',
    variants: { '2mg': { label: '2mg', price: 45 } },
    sizes: ['2mg'],
    purity: '≥99%',
    form: 'Lyophilized powder',
    storage: 'Store sealed lyophilized material per standard cold-storage protocols for peptide reagents.',
    cas: '863288-34-0',
    sequence: 'Modified GHRH(1-29)',
    molecularWeight: '3,647.1 g/mol',
    color: '#ec4899',
    categories: ['endocrine-research'],
    currentLot: 'RC-CJC26-0362',
    lotPurity: '99.4%',
    researchAreas: ['GHRH receptor binding', 'Endocrine signaling assays', 'Peptide stability studies', 'Analytical characterization'],
    mechanism: 'Modified GHRH(1-29) peptide reagent for in-vitro receptor research.',
    researchHighlights: [
      'No-DAC variant for discrete laboratory dosing studies',
      'HPLC-verified purity with MS confirmation',
      'Commonly referenced in endocrine signaling literature',
      'Research use only — not for human or animal consumption',
    ],
    reconstitution: 'Prepare per your laboratory standard operating procedures for lyophilized peptide reagents.',
    handling: 'Protect from light and moisture per institutional protocol.',
  },
  'ghk-cu': {
    id: 'ghk-cu',
    name: 'GHK-Cu',
    tagline: 'Copper(II)-GHK tripeptide — 50mg lyophilized vial',
    description: 'GHK-Cu — copper(II) complex of the GHK tripeptide, supplied in 50mg and 100mg lyophilized vials for in-vitro research.',
    longDescription: 'Copper(II)-GHK tripeptide complex supplied as a lyophilized powder for qualified extracellular matrix and collagen assay research in laboratory settings.',
    price: 35,
    defaultVariant: '50mg',
    variants: { '50mg': { label: '50mg', price: 35 }, '100mg': { label: '100mg', price: 58 } },
    sizes: ['50mg', '100mg'],
    purity: '≥99%',
    form: 'Lyophilized powder',
    storage: 'Store sealed lyophilized material per standard cold-storage protocols for peptide reagents.',
    cas: '49557-75-7',
    sequence: 'GHK-Cu²⁺',
    molecularWeight: '340.9 g/mol',
    color: '#06b6d4',
    categories: ['matrix-research'],
    currentLot: 'RC-GHK26-0395',
    lotPurity: '99.8%',
    researchAreas: ['Collagen synthesis assays', 'Matrix remodeling models', 'Gene expression studies', 'Analytical characterization'],
    mechanism: 'Copper(II)-GHK tripeptide complex for in-vitro matrix and collagen research assays.',
    researchHighlights: [
      'Higher-mass vials suited to matrix assay volumes',
      'HPLC-verified purity with MS confirmation',
      'Reference compound in extracellular matrix literature',
      'Research use only — not for human or animal consumption',
    ],
    reconstitution: 'Prepare per your laboratory standard operating procedures for lyophilized peptide reagents.',
    handling: 'Avoid incompatible reducing agents per institutional protocol.',
  },
  'recovery-stack': {
    id: 'recovery-stack',
    name: 'BPC-157 + TB-500 Pairing',
    tagline: 'Commonly studied pairing — two lyophilized vials',
    description: 'Commonly studied pairing: BPC-157 (5mg) and TB-500 (5mg) — separate lyophilized vials for in-vitro research.',
    longDescription: 'Two-compound research pairing containing one BPC-157 5mg vial and one TB-500 5mg vial. Each vial ships with its own batch-specific COA. For qualified laboratory research only.',
    price: 99,
    defaultVariant: 'bundle',
    isBundle: true,
    variants: { bundle: { label: 'BPC-157 5mg + TB-500 5mg', price: 99 } },
    sizes: ['Bundle'],
    purity: '≥99%',
    form: 'Lyophilized powder',
    storage: 'Store sealed lyophilized vials per standard cold-storage protocols.',
    cas: 'Bundle',
    sequence: '—',
    molecularWeight: '—',
    color: '#6366f1',
    categories: ['tissue-research'],
    currentLot: 'RC-RS26-0408',
    lotPurity: '99.6%',
    researchAreas: ['Multi-compound assay protocols', 'Analytical reference pairing', 'In-vitro model development'],
    mechanism: 'Two separate peptide reagents supplied together for multi-compound laboratory protocols.',
    researchHighlights: [
      'Separate vials — one BPC-157 5mg and one TB-500 5mg',
      'Individual COA for each compound',
      'Bundle pricing confirmed at checkout',
      'Research use only — not for human or animal consumption',
    ],
    reconstitution: 'Prepare each vial separately per your laboratory standard operating procedures.',
    handling: 'Store all vials sealed per institutional cold-storage requirements.',
  },
  'gh-stack': {
    id: 'gh-stack',
    name: 'Ipamorelin + CJC-1295 Pairing',
    tagline: 'Commonly studied pairing — two lyophilized vials',
    description: 'Commonly studied pairing: Ipamorelin (2mg) and CJC-1295 no DAC (2mg) — separate lyophilized vials for in-vitro research.',
    longDescription: 'Two-compound research pairing containing one Ipamorelin 2mg vial and one CJC-1295 2mg vial. Each vial ships with its own batch-specific COA. For qualified laboratory research only.',
    price: 72,
    defaultVariant: 'bundle',
    isBundle: true,
    variants: { bundle: { label: 'Ipamorelin 2mg + CJC-1295 2mg', price: 72 } },
    sizes: ['Bundle'],
    purity: '≥99%',
    form: 'Lyophilized powder',
    storage: 'Store sealed lyophilized vials per standard cold-storage protocols.',
    cas: 'Bundle',
    sequence: '—',
    molecularWeight: '—',
    color: '#a855f7',
    categories: ['endocrine-research'],
    currentLot: 'RC-GH26-0390',
    lotPurity: '99.5%',
    researchAreas: ['Dual-receptor assay protocols', 'Endocrine signaling models', 'Analytical reference pairing'],
    mechanism: 'Two separate peptide reagents supplied together for multi-pathway laboratory protocols.',
    researchHighlights: [
      'Separate vials — one Ipamorelin 2mg and one CJC-1295 2mg',
      'Individual COA for each compound',
      'Bundle pricing confirmed at checkout',
      'Research use only — not for human or animal consumption',
    ],
    reconstitution: 'Prepare each vial separately per your laboratory standard operating procedures.',
    handling: 'Store sealed per institutional cold-storage requirements.',
  },
};

window.PRODUCTS = PRODUCTS;
window.GOAL_CATEGORIES = GOAL_CATEGORIES;
window.GOAL_ALIASES = GOAL_ALIASES;